### ISSUE TITLE
Some Errors

### ISSUE THREAD

**Issue by SMRN** [nyu-dl/dl4mt-c2c#6]
Hi Jason,
Thanks for your paper and  sharing your code. Encountered the following errors:

----------------------------------
Traceback (most recent call last):
File "/home/prg/dl4mt-c2c-master/char2char/train_multi_char2char.py", line 173, in <module>
main(0, args)
 File "/home/prg/dl4mt-c2c-master/char2char/train_multi_char2char.py", line 94, in main
Model path:  /prg/dl4mt-c2c-master/DataSet/models/many_en/many_en/
 prepare_data=prepare_data,
File "/home/prg/dl4mt-c2c-master/char2char/nmt_many.py", line 135, in train
 with open(dd, 'rb') as f:
IOError: [Errno 2] No such file or directory: '/prg/dl4mt-c2c-master/DataSet/multi-wmt15/dic/source.404.pkl'

-----------------------------------------
but file source.404.pkl  is exist!

Thanks for your help.

**Comment by jaseleephd** [comment]
If you do `ls /prg/dl4mt-c2c-master/DataSet/multi-wmt15/dic/` can you see `source.404.pkl`?
you might be missing `/home` at the beginning of the path.

**Comment by SMRN** [comment]
yes. the file is exist in that folder. What about other errors?

**Comment by jaseleephd** [comment]
What other errors did you get? can you post them again

**Comment by SMRN** [comment]
3 errors:

File "/home/prg/dl4mt-c2c-master/char2char/train_multi_char2char.py", line 173, in
main(0, args)

File "/home/prg/dl4mt-c2c-master/char2char/train_multi_char2char.py", line 94, in main
Model path: /prg/dl4mt-c2c-master/DataSet/models/many_en/many_en/
prepare_data=prepare_data,

File "/home/prg/dl4mt-c2c-master/char2char/nmt_many.py", line 135, in train
with open(dd, 'rb') as f:

**Comment by jaseleephd** [comment]
I think those are the points in execution stacks that point to where exactly the first error occurred, rather than their own errors in themselves. 

Can you double check if you're giving the correct paths? Should be fairly straightforward to spot.

**Comment by SMRN** [comment]
i checked it again. i have changed some paths. it made a pkl file in the folder which is named models. then print "loading data" . after that:

File "/home/prg/dl4mt-c2c-master/char2char/train_bi_char2char.py", line 164, in main(0, args)

File "/home/prg/dl4mt-c2c-master/char2char/train_bi_char2char.py", line 84, in main
prepare_data=prepare_data.

File "/home/prg/dl4mt-c2c-master/char2char/nmt.py", line 235, in train build_model (tparams, model_options)

...

**Comment by jaseleephd** [comment]
Can you post the full error message? That way I have a better chance of figuring out what's going on. Cheers.

**Comment by SMRN** [comment]
Hi. I try to solve it today. If it doesn't work I will tell you. Thanks. It
must be work:)

**Comment by SMRN** [comment]
Dear jason Sorry for the late reply. I  checked and ran the program. One of errors is related to CUDA.
"CUDA not available". Are there other errors related to that?

**Comment by SMRN** [comment]
Dear Jason,
thanks for your help. it was related to CUDA.

**Comment by jaseleephd** [comment]
Please google any CUDA related issues. You should be able to find quick answers on stackoverflow

**Comment by SMRN** [comment]
thanks
